version: "3"

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB : dockerdb
      POSTGRES_USER : postgres
      POSTGRES_PASSWORD : TheSubMish
      POSTGRES_HOST : '127.0.0.1'
      POSTGRES_PORT : 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      SECRET : project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: {}
